name: talker
description: Advanced error handler and logger package for flutter and dart. App monitoring, logs history, report sharing, custom logs, and etc.
version: 4.8.1
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

topics:
  - logger
  - logging
  - error
  - exception
  - tool

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  talker_logger: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.1
