name: example
description: "Talker + Chopper Logger Example"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  talker_chopper_logger: ^5.0.1
  talker_flutter: ^5.0.1
  chopper: ^8.2.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  build_runner: ^2.4.15
  chopper_generator: ^8.1.0
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.1

dependency_overrides:
  talker_chopper_logger:
    path: ..
  talker_flutter:
    path: ../../talker_flutter

flutter:
  uses-material-design: true
