name: talker_riverpod_logger
description: Lightweight and customizable Riverpod state management library logger on talker base.
version: 5.1.2
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

topics:
  - riverpod
  - state
  - logging
  - log

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  talker: ^5.1.2
  riverpod: ^3.0.0
  meta: ^1.15.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
