name: talker_riverpod_logger
description: Lightweight and customizable Riverpod state management library logger on talker base.
version: 5.0.0
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

topics:
  - riverpod
  - state
  - logging
  - log

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  riverpod: ">=3.0.0 <4.0.0"
  talker: ^5.0.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.23.1
