name: talker_dio_logger
description: Lightweight and customizable dio http client logger on talker base
version: 1.3.0
homepage: https://github.com/Frezyx/talker

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dio: ^5.0.0
  talker: ^2.4.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.23.1
