name: talker_dio_logger
description: Lightweight and customizable dio http client logger on talker base
version: 5.1.3

homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

topics:
  - network
  - http
  - dio
  - logging
  - log

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  talker: ^5.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.23.1
