name: talker_dio_logger
description: Lightweight and customizable dio http client logger on talker base
version: 4.0.0-dev.4

homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

topics:
  - network
  - http
  - dio
  - logging
  - log

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  dio: ^5.2.0
  talker: ^4.0.0-dev.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.23.1
