name: talker_dio_logger
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  talker: ^1.3.0+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
