name: example
description: A sample command-line application.
version: 5.1.4
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  grpc: ^4.1.0
  talker: ^5.1.4
  talker_grpc_logger:
    path: ../

dev_dependencies:
  protoc_plugin: ^23.0.0
  lints: ^5.1.1
  test: ^1.24.0
