name: talker_grpc_logger
description: A lightweight, flexible grpc client logger built on the Talker platform, offering advanced exception handling and logging for Dart and Flutter applications.
version: 5.0.0-dev.12
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues


environment:
  sdk: ^3.2.6

dependencies:
  grpc: ^4.0.0
  talker: ^5.0.0-dev.12

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
