name: talker_shop_app_example
description: Talker flutter example shop application
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  talker: ^3.2.0
  talker_flutter: ^3.6.0
  talker_dio_logger: ^2.4.0
  talker_bloc_logger: ^2.4.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.4.0
  url_launcher: ^6.2.4
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
