name: talker_shop_app_example
description: Talker flutter example shop application
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: '>=2.17.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  talker_flutter: ^5.0.0-dev.11
  talker_dio_logger: ^5.0.0-dev.11
  talker_bloc_logger: ^5.0.0-dev.11
  
  get_it: ^7.6.7
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  dio: ^5.4.0
  url_launcher: ^6.3.1
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
