name: example
description: "Talker + Http Logger Example"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http_interceptor: ^2.0.0
  talker_http_logger:
  talker_flutter:
  equatable: ^2.0.7

dev_dependencies:
  flutter_lints: ^5.0.2

dependency_overrides:
  talker_http_logger:
    path: ..
  talker_flutter:
    path: ../../talker_flutter

flutter:
  uses-material-design: true
