name: talker_logger
description: Logger core package for talker (advanced error handler and logger package)
version: 3.0.0-dev.1
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1

dev_dependencies:
  lint: ^2.0.1
  test: ^1.22.1
