name: talker_logger
description: Logger. Easy, customizable, extensible logging, lightweight with filters, formatters, custom logs, log levels.
version: 4.5.2
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

topics:
  - logger
  - logging
  - log
  - console
  - cli

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  ansicolor: ^2.0.3

dev_dependencies:
  lint: ^2.3.0
  test: ^1.25.8
