name: talker_riverpod_example
publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crypto: ^3.0.6
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  riverpod: ^3.0.0
  talker_riverpod_logger: ^5.1.8

dev_dependencies:
  build_runner: ^2.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  test: ^1.26.3
