name: talker_http_logger
description: Lightweight and customizable http client logger on talker base
version: 5.0.0-dev.12
homepage: https://github.com/Frezyx/talker

environment:
  sdk: ^3.0.3

dependencies:
  equatable: ^2.0.7
  http_interceptor: ^2.0.0
  talker: ^5.0.0-dev.12
  meta: ^1.15.0

dev_dependencies:
  http_parser: ^4.1.2
  qs_dart: ^1.3.7+1
  lints: ^5.1.1
  test: ^1.25.15
