name: talker_riverpod_logger

on:
  push:
    paths:
      - "packages/talker_riverpod_logger/**"
      - ".github/workflows/talker_riverpod_logger.yaml"

  pull_request:
    paths:
      - "packages/talker_riverpod_logger/**"
      - ".github/workflows/talker_riverpod_logger.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/talker_riverpod_logger

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "12.x"
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze --fatal-infos --fatal-warnings .

      - name: Run tests
        run: flutter test --no-pub --coverage

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v3.0.0
        with:
          path: packages/talker_riverpod_logger/coverage/lcov.info
          min_coverage: 90

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # - name: Run Tests
      #   run: |
      #     pub global activate test_coverage
      #     export PATH=$PATH:$HOME/.pub-cache/bin
      #     test_coverage
      # - name: Check Code Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v3.0.0
      #   with:
      #     min_coverage: 30
      #     path: talker_bloc_logger_logger/coverage/lcov.info
