name: talker_bloc_logger
description: Lightweight and customizable BLoC state management library logger on talker base.
version: 4.6.4
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

topics:
  - bloc
  - state
  - cubit
  - logging
  - log

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  talker: ^4.6.4
  bloc: ^8.1.1
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
