name: talker_bloc_logger
description: Lightweight and customizable BLoC state management library logger on talker base.
version: 5.0.0-dev.11
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

topics:
  - bloc
  - state
  - cubit
  - logging
  - log

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  talker: ^5.0.0-dev.11
  bloc: ^9.0.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
