name: talker_flutter
description: Advanced error handler and logger package for flutter and dart. App monitoring, logs history, report sharing, custom logs, and etc.
version: 5.0.0-dev.8
homepage: https://github.com/Frezyx/talker
repository: https://github.com/Frezyx/talker
issue_tracker: https://github.com/Frezyx/talker/issues

topics:
  - logger
  - error
  - report
  - tool
  - ui

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  talker: ^5.0.0-dev.8
  group_button: ^5.3.4
  path_provider: ^2.1.4
  share_plus: ^11.0.0
  web: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
